In [1]:
import numpy as np


In [2]:
np.__version__

'2.2.4'

## Create & Read

### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5]) # 1D does not have rows and col
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape # printing nu. of element

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim # ndim = number of dimention array / output is 1/1D

1

In [8]:
arr1.size # array size

5

### 2D Array

In [9]:
arr2 = np.array([[1,4,5], [6,7,4]]) ## array inside array/nested array
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim  #number of dimention array / output is 2/2D

2

In [11]:
arr2.shape #(row,col)

(2, 3)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr2.size

6

### 3D Array

In [21]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3,4,5], [8,7,6]]])# Array inside array inside array

In [18]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]]])

In [19]:
arr3.ndim

3

In [20]:
arr3.shape # (2 is number of layers/2d array ,2 rows ,  3 col)

(2, 2, 3)

In [23]:
arr3 = np.array([[[1,4,5],[6,7,4]], [[3,4,5],[8,7,6]], [[1,4,5],[6,7,4]], [[3,4,5],[8,7,6]]])


In [24]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]],

       [[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]]])

In [25]:
arr3.shape

(4, 2, 3)

In [26]:
arr3.size

24

## Create Random Araay

In [27]:
randomArr = np.random.rand(3,2,3) # gives random array(3 layer , 2 row, 3 col)
randomArr

array([[[0.28373361, 0.40936696, 0.26434049],
        [0.61039028, 0.55299316, 0.93354204]],

       [[0.25124304, 0.10423687, 0.1869667 ],
        [0.30119362, 0.1259808 , 0.56965745]],

       [[0.91329937, 0.69047898, 0.94283153],
        [0.74621822, 0.23164816, 0.78812241]]])

In [28]:
randomArr.dtype

dtype('float64')

In [30]:
zeroes = np.zeros((3,2,3)) # pass all 0
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
zeroes.ndim

3

In [32]:
full = np.full((3,2,3), 8) # print all 8 layer,row ,col
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [33]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]],

       [[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]]])

In [37]:
arr3[0][0][2] # 0 index 0 index 2 index thats why print 5

np.int64(5)

In [38]:
arr3 [0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]]])

In [39]:
arr3 [0:3]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [40]:
arr3 [-1]

array([[3, 4, 5],
       [8, 7, 6]])

In [42]:
arr3[1][0][1] # 2nd layer, 1st row of 2nd layer, 2nd element of that row

np.int64(4)

In [43]:
arr3[1,0,1]

np.int64(4)

 ## Update & Delete

In [44]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [45]:
a1

array([[[0.56045398, 0.61884333],
        [0.90685106, 0.07506166],
        [0.09373315, 0.0391524 ]],

       [[0.64934452, 0.72057534],
        [0.32857268, 0.71868044],
        [0.98616303, 0.18795041]]])

In [46]:
a2

array([[[0.47380245, 0.21686934],
        [0.63933577, 0.51704304],
        [0.06927096, 0.0521127 ]],

       [[0.96711509, 0.24330111],
        [0.87936877, 0.95598808],
        [0.88853521, 0.12643325]]])

### Basic Math Operation

In [48]:
np.add(a1,a2) # add number element wise

array([[[1.03425643, 0.83571266],
        [1.54618682, 0.5921047 ],
        [0.16300411, 0.0912651 ]],

       [[1.61645961, 0.96387645],
        [1.20794145, 1.67466852],
        [1.87469824, 0.31438366]]])

In [49]:
np.subtract(a1,a2)

array([[[ 0.08665152,  0.40197399],
        [ 0.26751529, -0.44198137],
        [ 0.02446219, -0.01296031]],

       [[-0.31777057,  0.47727423],
        [-0.55079609, -0.23730764],
        [ 0.09762782,  0.06151715]]])

In [50]:
np.divide(a1,a2)

array([[[1.18288534, 2.8535308 ],
        [1.41842691, 0.14517488],
        [1.35313772, 0.75130237]],

       [[0.67142425, 2.96166069],
        [0.37364606, 0.75176716],
        [1.10987502, 1.48655834]]])

In [51]:
np.multiply(a1,a2)

array([[[0.26554447, 0.13420814],
        [0.57978232, 0.03881011],
        [0.00649299, 0.00204034]],

       [[0.62799088, 0.17531678],
        [0.28893655, 0.68704993],
        [0.87624058, 0.02376318]]])

### Statistical Operations

In [52]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8) # 2^8
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [53]:
sqrt

np.float64(5.0)

In [54]:
abs

np.int64(2)

In [55]:
power

np.int64(256)

In [56]:
log

np.float64(3.2188758248682006)

In [57]:
mins

np.float64(0.03915239765062495)

In [58]:
maxs

np.float64(0.96711508814261)

### Update

In [59]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]],

       [[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [8, 7, 6]]])

In [61]:
arr3[0,0,2] = 500 # 1st element,1st row,2nd index of col
arr3 # updating with a new value

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   4,   5],
        [  8,   7,   6]],

       [[  1,   4,   5],
        [  6,   7,   4]],

       [[  3,   4,   5],
        [  8,   7,   6]]])

In [62]:
arr3.sort() # sorting lower no to higher no
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  6,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  6,   7,   8]]])

In [63]:
# Reshape
arr3.shape

(4, 2, 3)

In [72]:
arr3_reshape = arr3.reshape((2, 3, 4)) # 2 layers,3 rows,4 col
arr3_reshape

array([[[  1,   4, 500,   4],
        [  6,   7,   3,   4],
        [  5,   6,   7,   8]],

       [[  1,   4,   5,   4],
        [  6,   7,   3,   4],
        [  5,   6,   7,   8]]])

In [73]:
arr3_reshape.shape

(2, 3, 4)

### Appending & Inserting

In [74]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appd = np.append(zeroes, new_array,axis = 0) # axis 0 = row axis 1 =col 
appd # append = 0 + 1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
# Insert


In [78]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [80]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [81]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.21418809, 0.0793405 , 0.96223358],
        [0.07555772, 0.54887102, 0.77214778]],

       [[0.6328631 , 0.81476398, 0.15224622],
        [0.20766564, 0.61741509, 0.90859032]],

       [[0.04925492, 0.11358961, 0.36627417],
        [0.02908273, 0.33826008, 0.8320739 ]]])

In [84]:
# delete the array
arr5= np.delete(arr4,0,axis=1)
arr5

array([[[0.07555772, 0.54887102, 0.77214778]],

       [[0.20766564, 0.61741509, 0.90859032]],

       [[0.02908273, 0.33826008, 0.8320739 ]]])

In [85]:
np.save("new_array", arr5)

In [86]:
np.load("new_array.npy")

array([[[0.07555772, 0.54887102, 0.77214778]],

       [[0.20766564, 0.61741509, 0.90859032]],

       [[0.02908273, 0.33826008, 0.8320739 ]]])